{
 "title": "Customer Feedback Pulse Dashboard",
 "description": "Sentiment Analysis and Response",
 "time": { "from": "2024-10-31T23:00:00.000Z", "to": "2024-12-31T22:59:59.000Z" },
 "panels": [
  {
   "title": "Total Reviews",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(review_count) AS total_reviews\nFROM response_trends\nWHERE $__timeFilter(trend_date)\n"
    }
   ]
  },
  {
   "title": "Avg. star rating",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(avg_star_rating) as avg_star_rating\nFROM response_trends\nWHERE $__timeFilter(trend_date)\n"
    }
   ]
  },
  {
   "title": "% Positive sentiment",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1.0 * SUM(CASE WHEN sentiment='Negative' THEN review_count ELSE 0 END) / SUM(review_count)\nFROM response_trends\nWHERE $__timeFilter(trend_date)\n"
    }
   ]
  },
  {
   "title": "Active Anomalies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) \nFROM response_trends\nWHERE $__timeFilter(trend_date)\nand anomaly = TRUE"
    }
   ]
  },
  {
   "title": "Escalations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(escalation_count) AS escalation_count\nFROM response_trends\nWHERE $__timeFilter(trend_date)\n"
    }
   ]
  },
  {
   "title": "Avg Start Rating Per Channel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(trend_date) AS day,\n  AVG(CASE WHEN channel = 'Google Maps' THEN avg_star_rating END) AS google_maps,\n  AVG(CASE WHEN channel = 'Facebook' THEN avg_star_rating END) AS facebook,\n  AVG(CASE WHEN channel = 'Instagram' THEN avg_star_rating END) AS instagram\nFROM\n  response_trends\nWHERE $__timeFilter(trend_date) \nGROUP BY\n  DATE(trend_date)\nORDER BY\n  day"
    }
   ]
  },
  {
   "title": "Reviews by Channel",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(review_count) as review_count, channel\nfrom response_trends\nWHERE $__timeFilter(trend_date)\nGROUP BY channel"
    }
   ]
  },
  {
   "title": "Avg Start Rating Per Location",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(trend_date) AS day,\n  AVG(CASE WHEN location = 'Downtown' THEN avg_star_rating END) AS Downtown,\n  AVG(CASE WHEN location = 'Midtown' THEN avg_star_rating END) AS Midtown,\n  AVG(CASE WHEN location = 'Uptown' THEN avg_star_rating END) AS Uptown\nFROM\n  response_trends\nWHERE $__timeFilter(trend_date) \nGROUP BY\n  DATE(trend_date)\nORDER BY\n  day"
    }
   ]
  },
  {
   "title": "Reviews by Location",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(review_count) as review_count, location\nfrom response_trends\nWHERE $__timeFilter(trend_date)\nGROUP BY location"
    }
   ]
  },
  {
   "title": "Escalations",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(review_date),\n  channel,\n  review_text review,\n  ai_response\nFROM processed_responses \nWHERE $__timeFilter(review_date)\nAND escalation\n"
    }
   ]
  }
 ]
}